services:
  node1:
    build:
      context: .
    hostname: node1
    container_name: mpi-node1
    environment:
      OMP_NUM_THREADS: 2
      OMPI_ALLOW_RUN_AS_ROOT: "1"
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: "1"
    networks:
      - mpi-net
    stdin_open: true
    tty: true

  node2:
    build:
      context: .
    hostname: node2
    container_name: mpi-node2
    environment:
      OMP_NUM_THREADS: 2
      OMPI_ALLOW_RUN_AS_ROOT: "1"
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: "1"
    networks:
      - mpi-net
    stdin_open: true
    tty: true

  node3:
    build:
      context: .
    hostname: node3
    container_name: mpi-node3
    environment:
      OMP_NUM_THREADS: 2
      OMPI_ALLOW_RUN_AS_ROOT: "1"
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: "1"
    networks:
      - mpi-net
    stdin_open: true
    tty: true

networks:
  mpi-net:
    driver: bridge
